networks:
  app:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local

# @see https://github.com/jaygaha/laravel-11-frankenphp-docker/blob/main/docker-compose.yml
# @see https://github.com/dunglas/symfony-docker/blob/main/compose.yaml
# @see https://frankenphp.dev/cn/docs/laravel/
services:
  app:
    build:
      context: .
      dockerfile: ./image/laravel/Dockerfile
      args:
        - ROOT_DIR=.
    restart: unless-stopped
    ports:
      # - "80:80" # HTTP
      # - "443:443" # HTTPS
      # - "443:443/udp" # HTTP3
      - "8000:8000" # HTTP
    volumes:
      - ./projects/api:/app
    networks:
      - app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      # minio:
      #   condition: service_healthy
      # mailpit:
      #   condition: service_healthy
    # healthcheck: # doesn't uncomment healthcheck when use app volumns
    #   test: [ "CMD", "curl http://localhost:8000/"]
    #   retries: 3
    #   timeout: 60s

  # dashboard:
  #   build:
  #     context: .
  #     dockerfile: ./image/dashboard/Dockerfile
  #     args:
  #       - ROOT_DIR=.
  #   restart: unless-stopped
  #   ports:
  #     - "8001:80" # HTTP
  #     # - "8001:3000" # HTTP
  #   depends_on:
  #     app:
  #       condition: service_healthy

  aves_blast:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./image/Aves_blast/Dockerfile
      args:
        - ROOT_DIR=.
    restart: unless-stopped
    volumes:
      - ./projects/Aves_blast:/app
    networks:
      - app
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mysql:
    image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
    restart: unless-stopped
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_HOST: ${DB_HOST:-%}
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

      MYSQL_ROOT_HOST: ${DB_HOST:-%}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-%}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - app
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p ${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ./data/redis:/data
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports:
      - "${RABBITMQ_NODE_HOST_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT:-15672}:15672"
    privileged: true
    networks:
      - app
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - ${MINIO_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-8900}:8900
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-root}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio_app}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio_app}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-http://127.0.0.1:9000}
      MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE:-public}
    volumes:
        - ./data/minio:/data
    networks:
      - app
    command: minio server /data/minio --console-address ":${MINIO_CONSOLE_PORT}"
    healthcheck:
      test: [ "CMD", "curl -f http://localhost:${MINIO_PORT}/minio/health/live"]
      retries: 3
      timeout: 5s

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
        - ${MAILPIT_PORT:-1025}:1025
        - ${MAILPIT_DASHBOARD_PORT:-8025}:8025
    volumes:
        - ./data/mail:/data
    networks:
        - app
